version: '3'

services:
  app:
    build: ./
    links:
      - banco
    networks:
      - rede
    ports:
      - "8080:5000"

  banco:      
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prod
      MYSQL_USER: dev
      MYSQL_PASSWORD: 1234
    networks:
      - rede
    ports:
      - "2020:3306"

networks:
  rede:
    driver: bridge