version: '3'

services:
  app:
    build: ./
    networks:
      - rede
    ports:
      - "8080:5000"

  mariadb:      
    image: mariadb:latest
    environment:
      MARIADB_MYSQL_LOCALHOST_USER: dev
      MARIADB_ROOT_PASSWORD: 123456
      MARIADB_DATABASE: prod
    networks:
      - rede
    ports:
      - "2020:3306"

networks:
  rede:
    driver: bridge
