version: '3'

services:
  app:
    build: ./
    networks:
      - rede
    ports:
      - "8080:5000"

  mysql:      
    image: mysql:latest
    environment:
      MYSQL_DATABASE: prod
      MYSQL_ALLOW_EMPTY_PASSWORD: 1234
    networks:
      - rede
    ports:
      - "2020:3306"

networks:
  rede:
    driver: bridge
